# -*- coding: utf-8 -*-
"""trabalhoNaive.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A9RwPzra0B3okEVdz-k706upcLhs9P8V
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, accuracy_score
from sklearn.model_selection import train_test_split
from IPython.display import display

SHEET_ID = "1g1aQ61vijh6uHJuc8sijeBEMsoIQ2a5yLwUK04Wptlg"
GID = "282951434"
url_csv = f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/export?format=csv&gid={GID}"

df = pd.read_csv(url_csv)

df = df.drop(columns=[df.columns[0]])

TARGET = df.columns[0]
FEATURES_RAW = list(df.columns[1:])

df[TARGET] = df[TARGET].astype(str).str.strip()

df = df.dropna(subset=FEATURES_RAW + [TARGET]).copy()

X_raw = df.drop(columns=[TARGET])
X = pd.get_dummies(X_raw, drop_first=True)

le = LabelEncoder()
y = le.fit_transform(df[TARGET])

RANDOM_STATE = 42
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=RANDOM_STATE, stratify=y
)

print(f"Treino: {len(X_train)} | Teste: {len(X_test)}")

nb_model = GaussianNB()

nb_model.fit(X_train, y_train)

y_pred_nb = nb_model.predict(X_test)

print("\n=== RESULTADOS NAIVE BAYES ===")
print("Acurácia:", accuracy_score(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb, target_names=le.classes_))

print("\nTabela de Resultados Detalhados (Real x Previsto pelo Naive Bayes):")

test_df_nb = df.loc[X_test.index].copy()
test_df_nb["classe_prevista"] = le.inverse_transform(y_pred_nb)

display(test_df_nb[FEATURES_RAW + [TARGET, "classe_prevista"]])