# -*- coding: utf-8 -*-
"""trabalhoArvore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gW5-5s00SbjubiPqYgi-P__WfEr-YN83
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import classification_report, accuracy_score
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

SHEET_ID = "1g1aQ61vijh6uHJuc8sijeBEMsoIQ2a5yLwUK04Wptlg"
GID = "282951434"
url_csv = f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/export?format=csv&gid={GID}"

df = pd.read_csv(url_csv)

df = df.drop(columns=[df.columns[0]])

TARGET = df.columns[0]
FEATURES_RAW = list(df.columns[1:])

df[TARGET] = df[TARGET].astype(str).str.strip()

df = df.dropna(subset=FEATURES_RAW + [TARGET]).copy()

X_raw = df.drop(columns=[TARGET])
X = pd.get_dummies(X_raw, drop_first=True)

le = LabelEncoder()
y = le.fit_transform(df[TARGET])

RANDOM_STATE = 42
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=RANDOM_STATE, stratify=y
)

print(f"Treino: {len(X_train)} | Teste: {len(X_test)}")

tree = DecisionTreeClassifier(
    max_depth=3,
    random_state=RANDOM_STATE
)

tree.fit(X_train, y_train)

y_pred_tree = tree.predict(X_test)

print("\n=== RESULTADOS ÁRVORE DE DECISÃO ===")
print("Acurácia:", accuracy_score(y_test, y_pred_tree))
print(classification_report(y_test, y_pred_tree, target_names=le.classes_))

plt.figure(figsize=(20, 10))
plot_tree(
    tree,
    feature_names=X.columns,
    class_names=list(le.classes_),
    filled=True,
    rounded=True
)
plt.title("Árvore de Decisão - Previsão de Gripe")
plt.show()