# -*- coding: utf-8 -*-
"""trabalhoRegras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_9uxKuFVEYXRGq9Dbwa1-Nl3A-XA__qe
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.metrics import classification_report, accuracy_score
from sklearn.model_selection import train_test_split

SHEET_ID = "1g1aQ61vijh6uHJuc8sijeBEMsoIQ2a5yLwUK04Wptlg"
GID = "282951434"
url_csv = f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/export?format=csv&gid={GID}"

df = pd.read_csv(url_csv)

df = df.drop(columns=[df.columns[0]])

TARGET = df.columns[0]
FEATURES_RAW = list(df.columns[1:])

df[TARGET] = df[TARGET].astype(str).str.strip()
df = df.dropna(subset=FEATURES_RAW + [TARGET]).copy()

X_raw = df.drop(columns=[TARGET])
X = pd.get_dummies(X_raw, drop_first=True)

le = LabelEncoder()
y = le.fit_transform(df[TARGET])

RANDOM_STATE = 42
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=RANDOM_STATE, stratify=y
)

print(f"Treino: {len(X_train)} | Teste: {len(X_test)}")

regras_model = DecisionTreeClassifier(
    max_depth=3,
    random_state=RANDOM_STATE
)

regras_model.fit(X_train, y_train)
y_pred_regras = regras_model.predict(X_test)

print("\n=== RESULTADOS: ALGORITMO DE REGRAS ===")
print("Acurácia:", accuracy_score(y_test, y_pred_regras))
print(classification_report(y_test, y_pred_regras, target_names=le.classes_))

print("\n=== CONJUNTO DE REGRAS GERADAS PELO MODELO ===")

regras_texto = export_text(
    regras_model,
    feature_names=list(X.columns),
    show_weights=True
)

regras_texto = regras_texto.replace("class: 0", f"ENTÃO A PREVISÃO É: {le.classes_[0]}")
regras_texto = regras_texto.replace("class: 1", f"ENTÃO A PREVISÃO É: {le.classes_[1]}")

print(regras_texto)