# -*- coding: utf-8 -*-
"""trabalhoKNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TPNawv65FUxfNtWEc4Ywu10ltRwvWRiq
"""

import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import classification_report, accuracy_score
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from IPython.display import display

SHEET_ID = "1g1aQ61vijh6uHJuc8sijeBEMsoIQ2a5yLwUK04Wptlg"
GID = "282951434"
url_csv = f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/export?format=csv&gid={GID}"

df = pd.read_csv(url_csv)

df = df.drop(columns=[df.columns[0]])

TARGET = df.columns[0]
FEATURES_RAW = list(df.columns[1:])

df[TARGET] = df[TARGET].astype(str).str.strip()

df = df.dropna(subset=FEATURES_RAW + [TARGET]).copy()

X_raw = df.drop(columns=[TARGET])
X = pd.get_dummies(X_raw, drop_first=True)

le = LabelEncoder()
y = le.fit_transform(df[TARGET])

RANDOM_STATE = 42
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=RANDOM_STATE, stratify=y
)

print(f"Treino: {len(X_train)} | Teste: {len(X_test)}")

K = 5
WEIGHTS = "distance"

model_knn = Pipeline(steps=[
    ("scaler", StandardScaler()),
    ("knn", KNeighborsClassifier(n_neighbors=K, weights=WEIGHTS))
])

model_knn.fit(X_train, y_train)

y_pred_knn = model_knn.predict(X_test)
print("\n=== RESULTADOS KNN (K=5) ===")
print("Acurácia:", accuracy_score(y_test, y_pred_knn))
print(classification_report(y_test, y_pred_knn, target_names=le.classes_))

print("\nTabela de Resultados Detalhados (Real x Previsto pelo KNN):")
test_df_knn = df.loc[X_test.index].copy()
test_df_knn["classe_prevista"] = le.inverse_transform(y_pred_knn)
display(test_df_knn[FEATURES_RAW + [TARGET, "classe_prevista"]])